name: CMake Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  # Добавьте macos-latest, windows-latest при необходимости
        cpp: [17]            # Матрица стандартов C++

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libgtest-dev
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp *.a /usr/lib

    - name: Cache GTest
      uses: actions/cache@v3
      with:
        path: /usr/local/lib/googletest
        key: ${{ runner.os }}-gtest

    - name: Build and Test Factorials
      working-directory: ./factorials-container
      run: |
        mkdir -p build && cd build
        cmake -DCMAKE_CXX_STANDARD=${{ matrix.cpp }} ..
        make
        ./FactorialsTest

    - name: Build and Test RemoveDuplicates
      working-directory: ./remove-duplicates
      run: |
        mkdir -p build && cd build
        cmake -DCMAKE_CXX_STANDARD=${{ matrix.cpp }} ..
        make
        ./DuplicatesRemoverTest

    - name: Build and Test ReverseLinkedList
      working-directory: ./reverse-linked-list
      run: |
        mkdir -p build && cd build
        cmake -DCMAKE_CXX_STANDARD=${{ matrix.cpp }} ..
        make
        ./LinkedListTest
