name: CMake Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++

    # Собираем и тестируем factorials-container
    - name: Build Factorials
      working-directory: ./factorials-container
      run: |
        mkdir -p build && cd build
        cmake -DCMAKE_CXX_STANDARD=17 ..
        make

    - name: Test Factorials
      working-directory: ./factorials-container/build
      run: ./FactorialsTest

    # Собираем и тестируем remove-duplicates
    - name: Build RemoveDuplicates
      working-directory: ./remove-duplicates
      run: |
        mkdir -p build && cd build
        cmake -DCMAKE_CXX_STANDARD=17 ..
        make

    - name: Test RemoveDuplicates
      working-directory: ./remove-duplicates/build
      run: ./DuplicatesRemoverTest

    # Собираем и тестируем reverse-linked-list
    - name: Build ReverseLinkedList
      working-directory: ./reverse-linked-list
      run: |
        mkdir -p build && cd build
        cmake -DCMAKE_CXX_STANDARD=17 ..
        make

    - name: Test ReverseLinkedList
      working-directory: ./reverse-linked-list/build
      run: ./LinkedListTest
